### ISSUE TITLE
Apresentação 

### ISSUE THREAD

**Issue by tricknp** [tricknp/Robocode#3]
Fala, pessoal. Tranquilo? 

Está issue sera destinada para apresentação de todos os membros da equipe.

Pra manter um padrão, vamos começar com uma breve apresentação pessoal, contendo: 

* Nome
* Posição no grupo (Coder ou Engineer)
* Contato

**Comment by tricknp** [comment]
Patrick Porto, Engineer.

* [Facebook](https://www.facebook.com/patrick.nporto)
* nporto.patrick@gmail.com

**Comment by mcj98** [comment]
Marcio Chagas, Coder.

[Facebook](https://www.facebook.com/marciochh)

**Comment by ghost** [comment]
Gabriel Vieira, Coder.

https://m.facebook.com/profile.php?ref=bookmarks

9810gabriel@gmail.com

**Comment by VitorHSR** [comment]
Vítor Hugo, Engineer

Facebook: https://m.facebook.com/vitorhugo.sellrodrigues

Email: vitorsellrs@gmail.com

**Comment by marcosmtt** [comment]
Marcos Motta, Engineer

**Facebook:** https://www.facebook.com/marcosmtt

**Email:** marcos.mottabtmn@gmail.com

**Comment by DanielMachadoGarcia** [comment]
Daniel Garcia, Engineer e coder
email: danielmgarcia32@gmail.com
