### ISSUE TITLE
Nome dos robôs

### ISSUE THREAD

**Issue by tricknp** [tricknp/Robocode#4]
Pessoal, os robôs devem ser inspirados em personagens da Marvel. 

Cada membro da equipe deve sugerir 3 nomes.

Caso precise, neste [link](http://universoanimanga.blogspot.com/2015/03/pagina-guia-lista-de-personagens-da.html) contem o nome de todos os personagens da Marvel

**Comment by tricknp** [comment]
* Wolwerine
* Noturno
* Deadpool

**Comment by mcj98** [comment]
Eu falei que queria o Thor kkkk, noturno.

**Comment by mcj98** [comment]
Thor, professor X, Magneto.

**Comment by VitorHSR** [comment]
- Adaga
- Loki
- Luke Cage

**Comment by marcosmtt** [comment]
Storm
Thanos
Black Panther

**Comment by DanielMachadoGarcia** [comment]
Hulk, Thanos e Doutor Estranho

**Comment by ghost** [comment]
Thanos
Groot
Thor

**Comment by tricknp** [comment]
Pessoal, os nomes escolhidos foram: 

* Thanos - 3 votos
* Thor - 2 votos
* Professor X - sorteado

Segue abaixo as foto do sorteio 

Primeiramente, separei os mais votados.
![captura de tela de 2018-06-14 22-04-12](https://user-images.githubusercontent.com/28790840/41445389-8efbdb7a-701f-11e8-86de-b57449647caf.png)

Em seguida coloquei o numero de personagens no sorteador
![captura de tela de 2018-06-14 22-05-24](https://user-images.githubusercontent.com/28790840/41445414-c0775594-701f-11e8-940a-8b02100a6384.png)

E o número escolhido foi...
![captura de tela de 2018-06-14 22-05-50](https://user-images.githubusercontent.com/28790840/41445419-cdabb69c-701f-11e8-81a4-4bdd84bca340.png)
