### ISSUE TITLE
Cores para os robôs

### ISSUE THREAD

**Issue by tricknp** [tricknp/Robocode#5]
Fala, pessoal. Tudo bem? 

Cada equipe irá ter um uniforme.

Qual a cor que vocês sugerem para a nossa equipe?

**Comment by tricknp** [comment]
Vermelho e preto

**Comment by mcj98** [comment]
Preto e vermelho. kappa

**Comment by DanielMachadoGarcia** [comment]
Azul e Cinza

**Comment by ghost** [comment]
Branco e Preto

**Comment by VitorHSR** [comment]
Amarelo e Preto

**Comment by marcosmtt** [comment]
Preto e vermelho

**Comment by tricknp** [comment]
Cores Escolhidas: Vermelho e preto.
