### ISSUE TITLE
Desenvolvimento do segundo robô

### ISSUE THREAD

**Issue by tricknp** [tricknp/Robocode#9]
Todo o andamento do processo de desenvolvimento do robô deve estar aqui.

**Comment by ghost** [comment]
[robocode.txt](https://github.com/tricknp/Robocode/files/2145759/robocode.txt)

**Comment by ghost** [comment]
Principal problema ta sendo movimentação, não to consigo programar ele pra fazer o caminho de lado a lado em "8".
